name: Docker Build and Push

on: 
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs: 
  build: 
    runs-on: ubuntu-latest # Fixed typo from `run-on` to `runs-on`

    steps: 
      # Step 1: Checkout the code 
      - name: Checkout Code 
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub 
      - name: Log in to Docker Hub 
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push Docker Image for each service 
      # Machine Learning Image
      - name: Build and Push ml_container Image 
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ml_container ./fast_service/ml_container 
          docker push ${{ secrets.DOCKER_USERNAME }}/ml_container

      # Security Image
      - name: Build and Push sec_container Image 
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sec_container ./fast_service/sec_container
          docker push ${{ secrets.DOCKER_USERNAME }}/sec_container

      # Blockchain Image
      - name: Build and Push block_container Image 
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/block_container ./node_service/block_container
          docker push ${{ secrets.DOCKER_USERNAME }}/block_container 

      # CRUD Image
      - name: Build and Push crud_container Image 
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/crud_container ./node_service/crud_container
          docker push ${{ secrets.DOCKER_USERNAME }}/crud_container 

      # Nginx Image (UI Service)
      - name: Build and Push ui_service Image 
        run: | 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ui_service .
          docker push ${{ secrets.DOCKER_USERNAME }}/ui_service

